
default:
  adapter: mysql2
  database: pottyproject
  username: tina
  password: tina
  host: localhost

 
development:
  adapter: mysql2
  database: pottyproject
  username: tina
  password: tina
  host: localhost
production:
  adapter: mysql2
  database: pottyproject
  username: tina
  password: tina
  host: localhost